In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/master/mtcars.csv')

In [14]:
df.head()

,Car Model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [ ]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [22]:
df.shape

(32, 12)

In [24]:
df = df.rename(columns= {'Unnamed: 0': 'Car Model'})

In [25]:
df2 = df[['mpg', 'cyl', 'hp', 'wt']]

In [26]:
df2 = df2.rename(columns= {'mpg' : 'miles per gallon', 'cyl' : 'cylinder', 'hp' : 'horse power', 'wt' : 'weight'})

In [27]:
df2.head()

   miles per gallon  cylinder  horse power  weight
0              21.0         6          110   2.620
1              21.0         6          110   2.875
2              22.8         4           93   2.320
3              21.4         6          110   3.215
4              18.7         8          175   3.440

In [ ]:
# summary for mpg
average_miles = df2['miles per gallon'].mean()
average_miles # average mpg is 20.09

median_miles = df2['miles per gallon'].median()
median_miles # median mpg is 19.2

19.2

In [ ]:
avg_cyl = df2['cylinder'].mean()
avg_cyl # average cylinder is 6.1875

med_cyl = df2['cylinder'].median()
med_cyl # median cylinder is 6

6.0

In [ ]:
avg_hp = df2['horse power'].mean()
avg_hp # average horse power is 146.6875

med_hp = df2['horse power'].median()
med_hp #median horse power is 123

123.0

In [ ]:
avg_weight = df2['weight'].mean()
avg_weight #average is 3.217

med_weight = df2['weight'].median()
med_weight #median is 3.325

3.325

In [19]:
df[df['Car Model'] == 'Honda Civic']

      Car Model   mpg  cyl  disp  hp  drat     wt   qsec  vs  am  gear  carb
18  Honda Civic  30.4    4  75.7  52  4.93  1.615  18.52   1   1     4     2